VERSION 0.8

deps:
    FROM golang:1.21-alpine3.18
    WORKDIR /libs/async
    COPY go.mod go.sum ./
    RUN go mod download

artifact:
    FROM +deps
    COPY zip_async.go .
    SAVE ARTIFACT .

unit-test:
    FROM +artifact
    COPY zip_async_test.go .
    RUN go test
